### ISSUE TITLE
'module' is not defined

### ISSUE THREAD

**Issue by shekky** [mattmccray/liquid.js#41]
Getting 'module' is not defined in dist version. Commenting out the last line seems to fix it though.

**Comment by lolmaus** [comment]
This line does not exist in `v1.3.0`.

Also, i can see that in sources there's proper checking for availability of `module`:

https://github.com/mattmccray/liquid.js/blob/master/source/core.js#L41

I wonder why this does not make it into dist.

**Comment by mattmccray** [comment]
This is fixed in the newly published version 1.3.2.
