### ISSUE TITLE
Accessing variables with space in name

### ISSUE THREAD

**Issue by thehappybug** [mattmccray/liquid.js#60]
Hello

I've tried really hard but I couldn't find any documentation about how to access a variable with space in it. This is important because I am binding to dictionary built from a JSON where spaces are allowed in the keys, hence my need for it.

I tried the accessor `foo['key name']` but this syntax does not work.

**Comment by mattmccray** [comment]
Sorry, not that I know of. It's because the original Ruby version of Liquid this is based on didn't support that.

>**Variables.** The most basic kind of expression is just the name of a variable. Liquid variables are named like Ruby variables: they should consist of alphanumeric characters and underscores, should always start with a letter, and do not have any kind of leading sigil (that is, they look like `var_name`, not `$var_name`).
